package report

import (
	"fmt"

	"github.com/easonliuuuuu/vsfleet/internal/assessment"
	"github.com/easonliuuuuu/vsfleet/internal/health"
)

// This file describes what the rvtools export profile writes: every worksheet,
// every column, the unit and type of each cell, and when a cell is left empty.
//
// It describes only what vsfleet emits. It makes no statement about RVTools'
// own schema, and deliberately does not enumerate columns RVTools has that this
// profile does not: that would require a reference copy of a proprietary
// schema, which this project does not have and does not want. The honest claim
// is "here is exactly what comes out, and here is what it means"; a pipeline
// owner compares that against their own requirements.
//
// Profile is generated by walking the real exporter output, and
// TestEveryExportedColumnIsDocumented fails the build if a column is added to a
// worksheet without describing it here. The report and the workbook therefore
// cannot drift apart.

// Cell kinds. These describe what a reader will find in the cell, in both the
// XLSX and CSV renderings — csvCell is the authority on how each is textualized.
const (
	KindText    = "text"
	KindInteger = "integer"
	KindDecimal = "decimal"
	KindBoolean = "boolean"
	KindDate    = "date"
)

// ColumnSpec describes one column of one worksheet.
type ColumnSpec struct {
	Name string `json:"column"`
	Kind string `json:"kind"`
	// Unit is the unit of measure, empty for unitless values.
	Unit string `json:"unit,omitempty"`
	// Empty says when the cell is left empty, empty itself when the column is
	// always populated.
	Empty string `json:"empty,omitempty"`
	Note  string `json:"note,omitempty"`
}

// SheetSpec describes one worksheet of the export.
type SheetSpec struct {
	Name string `json:"sheet"`
	// Compatible reports whether the worksheet is one of the RVTools-named
	// layouts this profile renders. vsfleetCoverage is vsfleet's own.
	Compatible bool `json:"rvtools_named"`
	// DerivesFrom names the collection the rows come from, matching the
	// vsfleetCoverage sheet's own accounting.
	DerivesFrom string       `json:"derives_from"`
	Note        string       `json:"note,omitempty"`
	Columns     []ColumnSpec `json:"columns"`
}

// Profile returns the full description of the rvtools export profile.
//
// It walks the actual sheet definitions rather than a parallel list: passing
// zero data through the exporter yields every worksheet with its real header
// row and no rows, which is the enumeration this report needs and cannot get
// out of step with.
func Profile() ([]SheetSpec, error) {
	sheets, err := rvtoolsSheets(assessment.ExportData{}, health.Report{})
	if err != nil {
		return nil, err
	}
	out := make([]SheetSpec, 0, len(sheets))
	for _, s := range sheets {
		meta := sheetMeta[s.name]
		spec := SheetSpec{
			Name:        s.name,
			Compatible:  s.name != coverageSheetName,
			DerivesFrom: meta.derivesFrom,
			Note:        meta.note,
			Columns:     make([]ColumnSpec, 0, len(s.headers)),
		}
		for _, header := range s.headers {
			col, ok := describeColumn(s.name, header)
			if !ok {
				return nil, fmt.Errorf("worksheet %s column %q has no description in compatibility.go", s.name, header)
			}
			spec.Columns = append(spec.Columns, col)
		}
		out = append(out, spec)
	}
	return out, nil
}

// describeColumn resolves one column, preferring a per-sheet description over
// the shared one. Names repeat across worksheets — "Capacity MiB" is a virtual
// disk on vDisk, a guest filesystem on vPartition and a datastore on
// vDatastore — so a shared table alone would describe some of them wrongly.
func describeColumn(sheet, name string) (ColumnSpec, bool) {
	if overrides, ok := sheetColumns[sheet]; ok {
		if col, ok := overrides[name]; ok {
			col.Name = name
			return col, true
		}
	}
	col, ok := sharedColumns[name]
	if !ok {
		return ColumnSpec{}, false
	}
	col.Name = name
	return col, true
}

type sheetInfo struct {
	derivesFrom string
	note        string
}

var sheetMeta = map[string]sheetInfo{
	"vInfo": {derivesFrom: "the VM collection", note: "One row per VM and per template."},
	"vCPU":  {derivesFrom: "the VM collection", note: "One row per VM. Configured vCPU count; this profile does not collect CPU performance counters."},
	"vMemory": {derivesFrom: "the VM collection",
		note: "One row per VM. Configured memory only; ballooned, shared and swapped figures are runtime performance counters this read-only profile does not request."},
	"vDisk": {derivesFrom: "the VM collection",
		note: "One row per virtual disk. Capacity is what vSphere provisioned; how much of it the guest has used is on vPartition, which vSphere cannot see without VMware Tools."},
	"vPartition": {derivesFrom: "the VM collection",
		note: "One row per guest filesystem. Only VMware Tools inside the guest can measure this, so a powered-off VM, or one whose Tools are not running, contributes no rows at all. vsfleetCoverage marks the tab partial and names how many VMs answered, so a short tab is never mistaken for a small estate."},
	"vNetwork":   {derivesFrom: "the VM collection", note: "One row per virtual NIC."},
	"vTools":     {derivesFrom: "the VM collection", note: "One row per VM. Captures taken before inventory schema 3 populate the running status but leave the version columns blank, and vsfleetCoverage records the gap."},
	"vHost":      {derivesFrom: "the host collection", note: "One row per ESXi host."},
	"vHBA":       {derivesFrom: "the host collection", note: "One row per host bus adapter. This profile reports adapter identity, transport details and protocol-specific names; it does not issue storage-system queries for target inventory."},
	"vNIC":       {derivesFrom: "the host collection", note: "One row per physical NIC. Link speed is empty when the link is down. Distributed-switch membership is collected on dvSwitch and dvPort."},
	"vSwitch":    {derivesFrom: "the host collection", note: "One row per standard virtual switch, including its effective security policy. Distributed virtual switches are on the separate dvSwitch sheet."},
	"vPort":      {derivesFrom: "the host collection", note: "One row per standard-switch port group. Security values are the effective computed policy after switch inheritance; distributed port groups are on dvPort."},
	"dvSwitch":   {derivesFrom: "the distributed switch collection", note: "One row per distributed virtual switch. Configuration and membership are collected from read-only vSphere properties; per-port runtime state is outside this profile."},
	"dvPort":     {derivesFrom: "the distributed switch collection", note: "One row per distributed port group and its default port policy, not one distributed port. Per-port runtime state is outside this read-only profile."},
	"vSC+VMK":    {derivesFrom: "the host collection", note: "One row per VMkernel or legacy service-console adapter. IP fields are empty when the host does not report them; distributed-switch-only connections are not expanded."},
	"vMultiPath": {derivesFrom: "the host collection", note: "One row per host and SCSI LUN with aggregate path states. Individual paths are counted rather than expanded, and this profile does not collect a separate target inventory."},
	"vCluster":   {derivesFrom: "the cluster collection", note: "One row per cluster. Standalone hosts appear as their own compute resource."},
	"vRP": {derivesFrom: "the resource pool collection",
		note: "One row per resource pool, including each cluster or standalone host's root Resources pool. vApps are reported on their own terms and are not duplicated here. Identity and CPU/memory allocation configuration only: this read-only capture does not request volatile runtime fields rather than guess at them. Captures before inventory schema 8 mark the tab not recorded."},
	"vDatastore": {derivesFrom: "the datastore collection", note: "One row per datastore."},
	"vSnapshot":  {derivesFrom: "the VM collection", note: "One row per snapshot, oldest first within a VM."},
	"vHealth": {derivesFrom: "the health rule engine",
		note: "One row per finding. Derived at export time from the stored evidence rather than collected, so re-exporting an unchanged run reproduces it exactly. assessment export always evaluates with the default thresholds; the tuning flags on `vsfleet health` do not apply to an export."},
	coverageSheetName: {derivesFrom: "the run ledger",
		note: "A vsfleet extension, not an RVTools worksheet. One row per worksheet per vCenter, naming what collected, what failed, and why. A partial estate is reported as partial rather than handed over as if it were whole."},
}

// sharedColumns describes every column whose meaning does not change between
// worksheets. The identity and provenance tail — Annotation through vsfleet
// Context — is the bulk of it, repeated on every per-VM tab.
var sharedColumns = map[string]ColumnSpec{
	// Per-VM identity and provenance tail.
	"VM":                                     {Kind: KindText, Note: "VM name as vCenter reports it; not unique across an estate."},
	"Powerstate":                             {Kind: KindText, Note: "poweredOn, poweredOff or suspended."},
	"Template":                               {Kind: KindBoolean, Note: "True for a VM template."},
	"Annotation":                             {Kind: KindText, Empty: "when the VM has no notes", Note: "Free text; may contain newlines."},
	"Datacenter":                             {Kind: KindText},
	"Cluster":                                {Kind: KindText, Empty: "for a VM on a standalone host"},
	"Host":                                   {Kind: KindText, Empty: "when vCenter reports no placement"},
	"Folder":                                 {Kind: KindText, Empty: "for a VM in the datacenter root", Note: "Inventory path below the datacenter's vm folder."},
	"OS according to the configuration file": {Kind: KindText, Note: "The configured guest OS identifier, which is what the VM claims to be — not what the guest actually runs."},
	"VM ID":                                  {Kind: KindText, Note: "vCenter managed object reference, e.g. vm-1042. Unique within one vCenter, not across an estate."},
	"VM UUID":                                {Kind: KindText, Note: "Instance UUID: unique to this VM instance, and the identifier vsfleet tracks a VM by across captures."},
	"VM SMBIOS UUID": {Kind: KindText, Empty: "when vCenter does not report one",
		Note: "The BIOS UUID the guest sees. It is preserved by a clone, so it is not a reliable unique key."},
	"VI SDK Server":   {Kind: KindText, Note: "The endpoint vsfleet was configured to reach, not a value vCenter reported."},
	"VI SDK UUID":     {Kind: KindText, Note: "The vCenter instance UUID, falling back to the endpoint string when vCenter omits it."},
	"vsfleet Context": {Kind: KindText, Note: "A vsfleet addition present on every worksheet: which configured context the row came from. It is what makes a single estate-wide workbook readable."},

	// vInfo.
	"Guest state":        {Kind: KindText, Empty: "when VMware Tools is not running", Note: "running or notRunning, as reported by Tools."},
	"CPUs":               {Kind: KindInteger, Note: "Configured vCPU count."},
	"Memory":             {Kind: KindInteger, Unit: "MiB", Note: "Configured memory."},
	"Primary IP Address": {Kind: KindText, Empty: "when VMware Tools reports no address"},
	"In Use MiB":         {Kind: KindInteger, Unit: "MiB", Note: "Committed storage across every disk, as vCenter reports it."},

	// vMemory.
	"Size MiB": {Kind: KindInteger, Unit: "MiB", Note: "Configured memory."},

	// vTools.
	"Tools":                {Kind: KindText, Note: "VMware Tools running status."},
	"Tools Version":        {Kind: KindText, Empty: "for a capture predating inventory schema 3, or when vCenter reports no version"},
	"Tools Version Status": {Kind: KindText, Empty: "for a capture predating inventory schema 3", Note: "e.g. guestToolsCurrent, guestToolsNeedUpgrade."},

	// vDisk.
	"Disk UUID":              {Kind: KindText, Empty: "when vSphere does not expose one"},
	"Disk Mode":              {Kind: KindText, Note: "e.g. persistent, independent_persistent."},
	"Sharing mode":           {Kind: KindText, Empty: "when vSphere does not expose one"},
	"Raw":                    {Kind: KindBoolean, Note: "True for a raw device mapping."},
	"Thin":                   {Kind: KindBoolean, Empty: "for a raw device mapping, where it does not apply"},
	"Eagerly Scrub":          {Kind: KindBoolean, Empty: "when vSphere does not expose it"},
	"Split":                  {Kind: KindBoolean, Empty: "when vSphere does not expose it"},
	"Write Through":          {Kind: KindBoolean, Empty: "when vSphere does not expose it"},
	"Controller":             {Kind: KindText, Empty: "when the controller cannot be resolved"},
	"SCSI label":             {Kind: KindText, Empty: "when the controller cannot be resolved"},
	"Unit number":            {Kind: KindInteger, Empty: "when vSphere does not expose one"},
	"SharedBus":              {Kind: KindText, Empty: "when the controller cannot be resolved", Note: "Controller bus sharing mode."},
	"Path":                   {Kind: KindText, Empty: "when the disk has no backing file", Note: "Datastore path, e.g. [datastore1] vm/vm.vmdk."},
	"Raw LUN ID":             {Kind: KindText, Empty: "for anything but a raw device mapping"},
	"Raw Compatibility Mode": {Kind: KindText, Empty: "for anything but a raw device mapping"},
	"Level":                  {Kind: KindText, Note: "Disk shares level: low, normal, high or custom."},
	"Shares":                 {Kind: KindInteger, Empty: "when vSphere does not expose it", Note: "Disk shares value."},
	"Reservation":            {Kind: KindInteger, Unit: "IOPS", Empty: "when vSphere does not expose it"},
	"Limit":                  {Kind: KindInteger, Unit: "IOPS", Empty: "when unlimited", Note: "-1 means unlimited where vSphere reports it that way."},

	// vPartition.
	"Consumed MiB": {Kind: KindDecimal, Unit: "MiB", Note: "Clamped to zero if VMware Tools reports free space exceeding capacity."},
	"Filesystem":   {Kind: KindText, Empty: "when VMware Tools does not report a type"},

	// vNetwork.
	"NIC label":        {Kind: KindText, Note: "e.g. Network adapter 1."},
	"Adapter":          {Kind: KindText, Note: "Virtual adapter type, e.g. VirtualVmxnet3."},
	"Network":          {Kind: KindText, Empty: "when the NIC is not attached", Note: "Port group name. This profile does not collect VLAN identifiers."},
	"Connected":        {Kind: KindBoolean, Note: "Whether the NIC is connected now."},
	"Starts Connected": {Kind: KindBoolean, Note: "Whether the NIC connects at power on."},
	"Mac Address":      {Kind: KindText},
	"Mac Address type": {Kind: KindText, Note: "e.g. assigned, manual."},
	"IPv4 Address":     {Kind: KindText, Empty: "when VMware Tools reports none", Note: "Several addresses are joined with \", \" in one cell."},
	"IPv6 Address":     {Kind: KindText, Empty: "when VMware Tools reports none", Note: "Several addresses are joined with \", \" in one cell."},
	"Direct Path IO":   {Kind: KindBoolean},

	// vHost.
	"in Maintenance Mode": {Kind: KindBoolean},
	"Speed":               {Kind: KindInteger, Unit: "MHz", Note: "Per-core clock speed."},
	"# Cores":             {Kind: KindInteger, Note: "Physical cores across every socket."},
	"CPU usage %":         {Kind: KindDecimal, Unit: "percent", Empty: "when the host reports no CPU capacity, rather than dividing by zero"},
	"# Memory":            {Kind: KindInteger, Unit: "MiB", Note: "Physical memory installed."},
	"Memory usage %":      {Kind: KindDecimal, Unit: "percent", Empty: "when the host reports no memory capacity, rather than dividing by zero"},
	"# VMs total":         {Kind: KindInteger},
	"ESX Version":         {Kind: KindText, Note: "Product version and build."},
	"Vendor":              {Kind: KindText},
	"Model":               {Kind: KindText},

	// vCluster.
	"NumHosts":          {Kind: KindInteger},
	"NumEffectiveHosts": {Kind: KindInteger, Note: "Hosts currently able to run VMs."},
	"TotalCpu":          {Kind: KindInteger, Unit: "MHz"},
	"NumCpuCores":       {Kind: KindInteger},
	"TotalMemory":       {Kind: KindInteger, Unit: "MiB"},
	"HA enabled":        {Kind: KindBoolean},
	"DRS enabled":       {Kind: KindBoolean},

	// vRP.
	"Resource pool":              {Kind: KindText, Note: "Inventory path of the pool."},
	"VMs":                        {Kind: KindInteger, Note: "VMs directly in this pool."},
	"vCPUs":                      {Kind: KindInteger, Note: "Sum of configured vCPUs across the VMs in this pool."},
	"CPU limit":                  {Kind: KindInteger, Unit: "MHz", Empty: "when unlimited"},
	"CPU overhead limit":         {Kind: KindInteger, Unit: "MHz", Empty: "when vSphere does not expose one"},
	"CPU reservation":            {Kind: KindInteger, Unit: "MHz", Empty: "when vSphere does not expose one"},
	"CPU level":                  {Kind: KindText, Note: "low, normal, high or custom."},
	"CPU shares":                 {Kind: KindInteger},
	"CPU expandable reservation": {Kind: KindBoolean},
	"Mem configured":             {Kind: KindInteger, Unit: "MiB"},
	"Mem limit":                  {Kind: KindInteger, Unit: "MiB", Empty: "when unlimited"},
	"Mem overhead limit":         {Kind: KindInteger, Unit: "MiB", Empty: "when vSphere does not expose one"},
	"Mem reservation":            {Kind: KindInteger, Unit: "MiB", Empty: "when vSphere does not expose one"},
	"Mem level":                  {Kind: KindText, Note: "low, normal, high or custom."},
	"Mem shares":                 {Kind: KindInteger},
	"Mem expandable reservation": {Kind: KindBoolean},
	"Config status":              {Kind: KindText, Note: "vSphere configuration status colour: green, yellow, red or gray."},

	// vDatastore.
	"Accessible":       {Kind: KindBoolean},
	"Maintenance mode": {Kind: KindText, Empty: "when vSphere does not expose one"},

	// vSnapshot.
	"Description": {Kind: KindText, Empty: "when the snapshot has no description"},
	"Date / time": {Kind: KindDate, Empty: "when vCenter reports no creation time",
		Note: "Rendered as a date cell in XLSX and as RFC3339 UTC in CSV."},
	"Quiesced": {Kind: KindBoolean, Note: "Whether the guest filesystem was quiesced."},
	"State":    {Kind: KindText, Note: "VM power state when the snapshot was taken."},

	// vHealth.
	"Message":        {Kind: KindText, Note: "What the rule found, in the operator's terms."},
	"Message type":   {Kind: KindText, Note: "Finding severity: info, warning or critical."},
	"Category":       {Kind: KindText, Note: "Finding category: migration, availability, security, capacity or hygiene."},
	"vsfleet Rule":   {Kind: KindText, Note: "A vsfleet addition: the rule identifier that produced the finding, so a finding can be traced to its threshold. List them with `vsfleet health --list-rules`."},
	"Recommendation": {Kind: KindText, Empty: "when the rule has no remediation guidance", Note: "The recommended operator action for this rule."},
	"Evidence":       {Kind: KindText, Empty: "when the finding has no structured evidence", Note: "Measured facts rendered as field=observed (expected value), joined with semicolons."},
	"Object type":    {Kind: KindText, Note: "What the finding is about: vm, host, datastore, cluster, dvswitch or another captured resource."},

	// vsfleetCoverage.
	"Run ID":      {Kind: KindInteger, Note: "The stored assessment this export was rendered from."},
	"Run label":   {Kind: KindText, Empty: "when the run was captured without --label"},
	"Run started": {Kind: KindDate, Note: "Rendered as a date cell in XLSX and as RFC3339 UTC in CSV."},
	"Run finished": {Kind: KindDate, Empty: "while a run is unfinished",
		Note: "Rendered as a date cell in XLSX and as RFC3339 UTC in CSV."},
	"Run status": {Kind: KindText, Note: "complete, partial or failed."},
	"Context":    {Kind: KindText, Note: "The configured vsfleet context this row accounts for."},
	"Endpoint":   {Kind: KindText},
	"vCenter ID": {Kind: KindText, Note: "vCenter instance UUID, falling back to the endpoint string."},
	"Sheet":      {Kind: KindText, Note: "The worksheet this row accounts for."},
	"Collection status": {Kind: KindText,
		Note: "success, empty, failed, partial, or \"not recorded\" when the capture predates the worksheet."},
	"Item count": {Kind: KindInteger, Note: "Rows this context contributed to that worksheet."},
	"Error":      {Kind: KindText, Empty: "when nothing went wrong", Note: "Why a collection failed, or what a partial one is missing."},
}

// sheetColumns describes columns whose meaning depends on the worksheet. A
// name here shadows the shared description for that sheet only.
var sheetColumns = map[string]map[string]ColumnSpec{
	"vDisk": {
		"Disk":         {Kind: KindText, Note: "Virtual disk label, e.g. Hard disk 1."},
		"Disk Key":     {Kind: KindInteger, Note: "Device key of the virtual disk. Joins to the column of the same name on vPartition."},
		"Capacity MiB": {Kind: KindDecimal, Unit: "MiB", Note: "Provisioned size of the virtual disk, which is not how much of it the guest has used."},
	},
	"vPartition": {
		"Disk": {Kind: KindText, Note: "Guest filesystem mount point or drive letter, e.g. / or C:\\."},
		"Disk Key": {Kind: KindText, Empty: "on estates before vSphere 7.0, where VMware Tools reports no mapping",
			Note: "The virtual disk behind this filesystem, joining to vDisk. A single key stays numeric so it matches vDisk's own numeric cell; a volume spanning several disks names each of them. An empty cell means unknown, never disk key zero."},
		"Capacity MiB": {Kind: KindDecimal, Unit: "MiB", Note: "Size of the guest filesystem, as VMware Tools measured it."},
		"Free MiB":     {Kind: KindDecimal, Unit: "MiB"},
		"Free %":       {Kind: KindDecimal, Unit: "percent", Note: "Rounded to two decimals. A filesystem VMware Tools reports with zero capacity is given 0 rather than an empty cell, because anything summing the column would read an empty cell as full."},
	},
	"vDatastore": {
		"Name":         {Kind: KindText, Note: "Datastore name."},
		"Type":         {Kind: KindText, Note: "e.g. VMFS, NFS, vsan."},
		"Capacity MiB": {Kind: KindDecimal, Unit: "MiB", Note: "Total datastore capacity."},
		"Free MiB":     {Kind: KindDecimal, Unit: "MiB"},
		"Free %":       {Kind: KindDecimal, Unit: "percent", Empty: "when the datastore reports no capacity, rather than dividing by zero"},
		"Object ID":    {Kind: KindText, Note: "vCenter managed object reference of the datastore."},
	},
	"vCluster": {
		"Name":      {Kind: KindText, Note: "Cluster name."},
		"Object ID": {Kind: KindText, Note: "vCenter managed object reference of the cluster."},
	},
	"vRP": {
		"Name":      {Kind: KindText, Note: "Resource pool name, the last element of the Resource pool path."},
		"Status":    {Kind: KindText, Note: "vSphere overall status colour: green, yellow, red or gray."},
		"Object ID": {Kind: KindText, Note: "vCenter managed object reference of the resource pool."},
	},
	"vHost": {
		"Host":      {Kind: KindText, Note: "ESXi host name."},
		"Object ID": {Kind: KindText, Note: "vCenter managed object reference of the host."},
	},
	"vHBA": {
		"Device":           {Kind: KindText, Note: "Host bus adapter device name, for example vmhba0."},
		"Bus":              {Kind: KindInteger, Note: "Host bus number."},
		"Status":           {Kind: KindText, Note: "Adapter operational status as vSphere reports it."},
		"Model":            {Kind: KindText, Note: "Host bus adapter model."},
		"Driver":           {Kind: KindText, Empty: "when vSphere does not report a driver"},
		"PCI":              {Kind: KindText, Empty: "when vSphere does not report a PCI identifier"},
		"Storage protocol": {Kind: KindText, Note: "Storage protocol reported by the adapter; vSphere's omitted default is shown as scsi."},
		"WWNN":             {Kind: KindInteger, Empty: "for adapters that do not expose a Fibre Channel node WWN"},
		"WWPN":             {Kind: KindInteger, Empty: "for adapters that do not expose a Fibre Channel port WWN"},
		"iSCSI name":       {Kind: KindText, Empty: "for adapters that are not iSCSI, or when no iSCSI name is reported"},
		"iSCSI alias":      {Kind: KindText, Empty: "when the iSCSI adapter has no alias"},
		"Type":             {Kind: KindText, Note: "Concrete vSphere adapter type, such as HostFibreChannelHba or HostBlockHba."},
		"Host":             {Kind: KindText, Note: "ESXi host that owns the adapter."},
		"Cluster":          {Kind: KindText, Empty: "for a standalone host"},
		"Object ID":        {Kind: KindText, Note: "vCenter managed object reference of the host."},
	},
	"vNIC": {
		"Device":        {Kind: KindText, Note: "Physical NIC device name, for example vmnic0."},
		"PCI":           {Kind: KindText, Empty: "when vSphere does not report a PCI identifier"},
		"Driver":        {Kind: KindText, Empty: "when vSphere does not report a driver"},
		"Mac Address":   {Kind: KindText, Empty: "when vSphere does not report a MAC address"},
		"Link speed Mb": {Kind: KindInteger, Unit: "Mb/s", Empty: "when the physical link is down or vSphere reports no link state"},
		"Duplex":        {Kind: KindBoolean, Empty: "when the physical link is down or vSphere reports no link state"},
		"Wake on LAN":   {Kind: KindBoolean, Note: "Whether the physical NIC supports wake on LAN."},
		"Switch":        {Kind: KindText, Empty: "when the physical NIC is not attached to a standard virtual switch"},
		"Host":          {Kind: KindText, Note: "ESXi host that owns the NIC."},
		"Cluster":       {Kind: KindText, Empty: "for a standalone host"},
		"Object ID":     {Kind: KindText, Note: "vCenter managed object reference of the host."},
	},
	"vSwitch": {
		"Switch":           {Kind: KindText, Note: "Standard virtual switch name."},
		"# Ports":          {Kind: KindInteger, Note: "Number of ports currently on the switch."},
		"Free ports":       {Kind: KindInteger, Note: "Ports available for new services."},
		"MTU":              {Kind: KindInteger, Unit: "bytes", Note: "Maximum transmission unit."},
		"Uplinks":          {Kind: KindText, Empty: "when the switch has no physical uplinks", Note: "Physical NIC keys joined with comma-space."},
		"Promiscuous mode": {Kind: KindBoolean, Empty: "when the switch does not report a security policy"},
		"MAC changes":      {Kind: KindBoolean, Empty: "when the switch does not report a security policy"},
		"Forged transmits": {Kind: KindBoolean, Empty: "when the switch does not report a security policy"},
		"Traffic shaping":  {Kind: KindBoolean, Empty: "when the switch does not report a shaping policy"},
		"Host":             {Kind: KindText, Note: "ESXi host that owns the switch."},
		"Cluster":          {Kind: KindText, Empty: "for a standalone host"},
		"Object ID":        {Kind: KindText, Note: "vCenter managed object reference of the host."},
	},
	"vPort": {
		"Port group":       {Kind: KindText, Note: "Standard-switch port group name."},
		"Switch":           {Kind: KindText, Empty: "when vSphere does not report the parent switch"},
		"VLAN":             {Kind: KindInteger, Note: "VLAN ID; 0 means untagged and 4095 means trunk mode."},
		"Promiscuous mode": {Kind: KindBoolean, Empty: "when the computed port-group security policy omits it"},
		"MAC changes":      {Kind: KindBoolean, Empty: "when the computed port-group security policy omits it"},
		"Forged transmits": {Kind: KindBoolean, Empty: "when the computed port-group security policy omits it"},
		"Host":             {Kind: KindText, Note: "ESXi host that owns the port group."},
		"Cluster":          {Kind: KindText, Empty: "for a standalone host"},
		"Object ID":        {Kind: KindText, Note: "vCenter managed object reference of the host."},
	},
	"dvSwitch": {
		"DVS":                      {Kind: KindText, Note: "Distributed virtual switch name."},
		"# Ports":                  {Kind: KindInteger, Note: "Current distributed ports on the switch."},
		"# Max ports":              {Kind: KindInteger, Note: "Configured maximum number of distributed ports."},
		"MTU":                      {Kind: KindInteger, Unit: "bytes", Note: "Maximum transmission unit configured for the switch."},
		"Vendor":                   {Kind: KindText, Empty: "when the switch does not report product information"},
		"Version":                  {Kind: KindText, Empty: "when the switch does not report product information"},
		"UUID":                     {Kind: KindText, Empty: "when vSphere does not report a switch UUID"},
		"Description":              {Kind: KindText, Empty: "when the switch has no description"},
		"Contact":                  {Kind: KindText, Empty: "when the switch has no contact name"},
		"Contact detail":           {Kind: KindText, Empty: "when the switch has no contact detail"},
		"Hosts":                    {Kind: KindText, Empty: "when no hosts are members", Note: "Host names joined with comma-space."},
		"Uplink ports":             {Kind: KindText, Empty: "when no uplink port groups are reported", Note: "Uplink port-group names joined with comma-space."},
		"Link discovery protocol":  {Kind: KindText, Empty: "when the switch has no link discovery configuration"},
		"Link discovery operation": {Kind: KindText, Empty: "when the switch has no link discovery configuration"},
		"LACP version":             {Kind: KindText, Empty: "when the switch has no LACP API version"},
		"Datacenter":               {Kind: KindText, Note: "Datacenter containing the distributed switch."},
		"Object ID":                {Kind: KindText, Note: "vCenter managed object reference of the distributed switch."},
		"VI SDK Server":            {Kind: KindText},
		"VI SDK UUID":              {Kind: KindText},
		"vsfleet Context":          {Kind: KindText},
	},
	"dvPort": {
		"Port group":          {Kind: KindText, Note: "Distributed port-group name."},
		"DVS":                 {Kind: KindText, Note: "Parent distributed virtual switch name."},
		"Key":                 {Kind: KindText, Note: "Distributed port-group key."},
		"Type":                {Kind: KindText, Empty: "when vSphere does not report a port-group binding type"},
		"Backing type":        {Kind: KindText, Empty: "when vSphere does not report a backing type"},
		"# Ports":             {Kind: KindInteger, Note: "Configured number of ports in the group."},
		"VLAN":                {Kind: KindText, Empty: "when no default VLAN specification is reported", Note: "A VLAN ID, trunk range, or pvlan value."},
		"Uplink":              {Kind: KindBoolean},
		"Promiscuous mode":    {Kind: KindBoolean, Empty: "when the default security policy omits it"},
		"MAC changes":         {Kind: KindBoolean, Empty: "when the default security policy omits it"},
		"Forged transmits":    {Kind: KindBoolean, Empty: "when the default security policy omits it"},
		"Teaming policy":      {Kind: KindText, Empty: "when no default teaming policy is reported"},
		"Notify switches":     {Kind: KindBoolean, Empty: "when no default teaming policy is reported"},
		"Failback":            {Kind: KindBoolean, Empty: "when no default teaming policy is reported"},
		"Ingress shaping":     {Kind: KindBoolean, Empty: "when no ingress shaping policy is reported"},
		"Egress shaping":      {Kind: KindBoolean, Empty: "when no egress shaping policy is reported"},
		"Blocked":             {Kind: KindBoolean, Empty: "when the default port policy omits it"},
		"Auto expand":         {Kind: KindBoolean, Empty: "when the port group does not report auto-expansion"},
		"Active uplinks":      {Kind: KindText, Empty: "when no active uplinks are reported"},
		"Standby uplinks":     {Kind: KindText, Empty: "when no standby uplinks are reported"},
		"Logical switch UUID": {Kind: KindText, Empty: "for a port group without NSX backing"},
		"Segment ID":          {Kind: KindText, Empty: "for a port group without NSX backing"},
		"Datacenter":          {Kind: KindText, Note: "Datacenter containing the parent distributed switch."},
		"Object ID":           {Kind: KindText, Note: "vCenter managed object reference of the parent distributed switch."},
		"VI SDK Server":       {Kind: KindText},
		"VI SDK UUID":         {Kind: KindText},
		"vsfleet Context":     {Kind: KindText},
	},
	"vSC+VMK": {
		"Device":          {Kind: KindText, Note: "VMkernel or service-console device, for example vmk0."},
		"Port group":      {Kind: KindText, Empty: "when the adapter is connected to a distributed or opaque network"},
		"Mac Address":     {Kind: KindText, Empty: "when vSphere does not report a MAC address"},
		"MTU":             {Kind: KindInteger, Unit: "bytes"},
		"TSO":             {Kind: KindBoolean, Empty: "when vSphere does not report TCP segmentation offload state"},
		"Netstack":        {Kind: KindText, Empty: "when vSphere does not report a network stack"},
		"DHCP":            {Kind: KindBoolean, Empty: "when the adapter has no IP configuration"},
		"IP Address":      {Kind: KindText, Empty: "when the adapter has no reported IPv4 address"},
		"Subnet mask":     {Kind: KindText, Empty: "when the adapter has no reported IPv4 configuration"},
		"Service console": {Kind: KindBoolean, Note: "True when the adapter came from HostNetworkInfo.ConsoleVnic rather than Vnic."},
		"Host":            {Kind: KindText, Note: "ESXi host that owns the adapter."},
		"Cluster":         {Kind: KindText, Empty: "for a standalone host"},
		"Object ID":       {Kind: KindText, Note: "vCenter managed object reference of the host."},
	},
	"vMultiPath": {
		"LUN":            {Kind: KindText, Note: "SCSI LUN display name, falling back to its canonical name or device name."},
		"Device path":    {Kind: KindText, Empty: "when the resolved ScsiLun has no device name"},
		"Policy":         {Kind: KindText, Empty: "when vSphere reports no multipath policy"},
		"Path count":     {Kind: KindInteger, Note: "Total paths to this LUN; paths are aggregated into one row."},
		"Active paths":   {Kind: KindInteger},
		"Standby paths":  {Kind: KindInteger},
		"Dead paths":     {Kind: KindInteger},
		"Disabled paths": {Kind: KindInteger},
		"Working paths":  {Kind: KindInteger, Note: "Paths marked as working by the path-selection policy."},
		"Host":           {Kind: KindText, Note: "ESXi host that owns the LUN paths."},
		"Cluster":        {Kind: KindText, Empty: "for a standalone host"},
		"Object ID":      {Kind: KindText, Note: "vCenter managed object reference of the host."},
	},
	"vHealth": {
		"Name":      {Kind: KindText, Note: "Name of the object the finding is about."},
		"Object ID": {Kind: KindText, Empty: "when the finding is not about a single managed object"},
	},
	"vSnapshot": {
		"Name": {Kind: KindText, Note: "Snapshot name."},
	},
}
